[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.146.0"
  NODE_VERSION = "18"
  GO_VERSION = "1.21"

[context.production.environment]
  HUGO_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-hugo"
